version: 0.2

phases:
  install:
    commands:
      #install node
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist